version: 2
jobs:
   build-job:
     docker:
       - image: circleci/ruby:latest
     steps:
       - checkout
       - run: echo "Build finished!"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job